name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
  publish:
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-tags: true
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Set git credentials
        run: |
          git fetch --tags
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Bump version based off tag name
        run: |
          npm config set git-tag-version false
          npm version from-git
          git add .
          git commit -m "bump: $GITHUB_REF_NAME"
          git push
        working-directory: types-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies for payload
        run: npm ci
      - name: Publish generated types from payload to npm 
        run: |
          npm ci
          npm publish
        working-directory: types-package
